#         __  __ _ _
#  _   _|  \/  (_) |_ ___
# | | | | |\/| | | __/ _ \
# | |_| | |  | | | || (_) |
#  \__, |_|  |_|_|\__\___/
#  |___/
# Discord: discord.ystoreplugins.com.br
# Site: ystoreplugins.com.br
#

# Modo de depuração para correção de problemas no plugin.
debug-mode: false

#      ___      _        _
#     /   \__ _| |_ __ _| |__   __ _ ___  ___
#    / /\ / _` | __/ _` | '_ \ / _` / __|/ _ \
#   / /_// (_| | || (_| | |_) | (_| \__ \  __/
#  /___,' \__,_|\__\__,_|_.__/ \__,_|___/\___|
#
# Configurações do banco de dados.

database:
  # Determina o tipo de banco de dados. Valores válidos: [SQLITE, MYSQL, HIKARI (recomendado)]
  storage-type: SQLITE

  # Dados para conexão ao banco de dados MYSQL.
  data:
    # Endereço de conexão do banco de dados. [EX: 127.0.0.1]
    host: localhost
    # Porta de conexão do banco de dados. [EX: 3306]
    port: 3306
    # Nome do banco de dados a ser conectado. [EX: minecraft]
    database: ''
    # Usuário de conexão. [EX: root]
    username: ''
    # Senha do usuário de conexão: [EX: 123]
    password: ''

# Sistemas gerais do plugin
general:
  # Tag do Mito
  tag: '&5[MITO]'
  # Ativar abrir o menu ao digitar /mito
  mito-menu: true
  # Ativar o sistema de perder mito por inatividade
  lose: true
  # Tempo inativo no servidor para perder o Mito
  # em segundos
  time-lose: 30
  # Perder o mito por tempo apenas se tiver outro jogador on
  lose-has-player: true
  # Tempo que o jogador pode morrer sem perder a tag após recebê-la
  # em segundos
  cooldown-lose-death: 30

effect:
  # Soltar efeito de raio no novo mito
  strike-lightning: true
  # Spawnar morcegos ao redor do novo mito
  spawn-bats: true
  # Tocar som no novo mito
  sound: 'ENDERDRAGON_GROWL'

# Recompensas por matar o mito
rewards:
  amount: 1
  list:
    - '100.0,give {player} diamond 1'

# Comandos executados no mito
commands:
  - 'give {new} diamond 1'
  - 'give {old} stone 1'

# Configurações do npc
npc:
  # Altura do holograma
  off-set: 3.1
  hologram:
    - '&c&lMITO'
    - '&7Mito Atual &c{player}&7.'